# Generated by Django 5.1.3 on 2024-12-03 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='data_criacao',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
