# Generated by Django 5.1.3 on 2024-11-29 17:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pequeno_negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=50)),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('despesas_fixas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('despesas_variaveis', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(default=datetime.datetime.today)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150)),
                ('quantidade_de_produto_vendido', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_da_venda', models.DateField(default=datetime.datetime.today)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Informacoes_bancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.IntegerField()),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('codigo_confirmacao', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_bancarias', to='contas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Financas_pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos_fixos_mensais', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos_variaveis_mensais', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_investimentos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_dividas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_objeto_financeiro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financas', to='contas.usuario')),
            ],
        ),
    ]
