# Generated by Django 5.1.3 on 2024-12-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Financas_pessoas',
        ),
    ]
